name: Deploy to EC2

on:
  push:
    branches: main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ec2-54-82-139-186.compute-1.amazonaws.com # Host is the public DNS of the instance
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }} # PRIVATE_SSH_KEY, is the keyname which I gave to the ssh key as Repository secrets in the github actions key in the settings tab
          port: 22
          script: |
            ls
            cd Nextjs-with-cicd
            git pull
            npm install 
            npm run build
            npm run start
